/** user operations on books */
export const FETCH_BOOKS = 'FETCH_BOOKS';
export const FETCHING_BOOKS = 'FETCHING_BOOKS';
export const SHOW_BOOK_DETAILS = 'SHOW_BOOK_DETAILS';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const RESERVE_BOOK = 'RESERVE_BOOK';
export const RESERVE_BOOK_SUCCESS = 'RESERVE_BOOK_SUCCESS';
export const RETURN_BOOK = 'RETURN_BOOK';
export const RETURN_BOOK_SUCCESS = 'RETURN_BOOK_SUCCESS';
export const FETCH_MY_BOOKS = 'FETCH_MY_BOOKS';

/** Manage Books start */
export const FETCH_PENDING_ISSUE_BOOKS = 'FETCH_PENDING_ISSUE_BOOKS';
export const APPROVE_FETCH_BOOK_SUCCESS = 'APPROVE_FETCH_BOOK_SUCCESS';
export const REJECT_ISSUE_REQUEST_BOOK = 'REJECT_ISSUE_REQUEST_BOOK';
export const FETCH_ALL_BOOKS_SUCCESS = 'FETCH_ALL_BOOKS_SUCCESS';
export const DELETE_BOOK = 'DELETE_BOOK';
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
export const ADD_BOOK = 'ADD_BOOK';
export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS';

/** Authentication */
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCESS = 'AUTH_SUCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT = 'SET_AUTH_REDIRECT';